version: "3.9"

services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - "8080:8080"
    # IMPORTANT env vars:
    environment:
      # Create the default user and a fixed API token usable by bootstrap:
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}
      - LABEL_STUDIO_USER_TOKEN=${LABEL_STUDIO_USER_TOKEN}
      - LABEL_STUDIO_ENABLE_LEGACY_API_TOKEN=true
      # Enable local file serving and restrict the root:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      # (optional) host name for links in emails etc.
      - LABEL_STUDIO_HOST=${PUBLIC_URL}
    command: ["label-studio", "start", "--host", "0.0.0.0", "--port", "8080"]
    volumes:
      # Persist Label Studio internal data (DB, uploads, configs)
      - ./mydata:/label-studio/data
      # Mount your image repository read-only inside the container
      # NOTE: Windows path on the left side:
      - ${HOST_REPOSITORY_PATH}:/label-studio/files/pampas_repository:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/version"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  bootstrap:
    image: curlimages/curl:8.10.1
    container_name: bootstrap
    depends_on:
      labelstudio:
        condition: service_healthy
    environment:
      - LS_BASE=http://labelstudio:8080
      - LS_USER=${LABEL_STUDIO_USERNAME}
      - LS_PASS=${LABEL_STUDIO_PASSWORD}
      - PROJECT_TITLE=${PROJECT_TITLE}
      - PROJECT_DESC=${PROJECT_DESC}
      - LOCAL_SOURCE_PATH=/label-studio/files/pampas_repository
      - LS_TOKEN=${LABEL_STUDIO_USER_TOKEN}
    volumes:
      - ./bootstrap:/bootstrap:ro
    entrypoint: ["/bin/sh","-c","/bootstrap/bootstrap.sh"]
    # Run once and exit
    restart: "no"